<html>
<body>
<h2>/AllShopRest/rest/CatalogoCorporativo</h2>
/CatalogoCorporativo/SubCategoria<br>
/CatalogoCorporativo/Producto<br>
/CatalogoCorporativo/Producto<br>
/CatalogoCorporativo/Producto/{idProducto}<br>
/CatalogoCorporativo/Pago<br>
/CatalogoCorporativo/Pago<br>
/CatalogoCorporativo/Pago/{idPago}<br>
/CatalogoCorporativo/Moneda<br>
/CatalogoCorporativo/Moneda<br>
/CatalogoCorporativo/Moneda/{iMoneda}<br>
/CatalogoCorporativo/Lenguaje<br>
/CatalogoCorporativo/Lenguaje<br>
/CatalogoCorporativo/Lenguaje/{idLenguaje}<br>
/CatalogoCorporativo/Desarrollo<br>
/CatalogoCorporativo/Cuenta<br>
/CatalogoCorporativo/Cuenta<br>
/CatalogoCorporativo/Cuenta/{idCuenta}<br>
/CatalogoCorporativo/Categoria<br>
/CatalogoCorporativo/Categoria<br>
/CatalogoCorporativo/Categoria/{idCategoria}<br>
/CatalogoCorporativo/Calificacion<br>
/CatalogoCorporativo/Rol<br>
/CatalogoCorporativo/Rol<br>
/CatalogoCorporativo/Rol/GenericConsultaRequest<br>
/CatalogoCorporativo/SubCategoria<br>
/CatalogoCorporativo/SubCategoria/{idSubCategoria}<br>
/CatalogoCorporativo/Desarrollo<br>
/CatalogoCorporativo/Desarrollo/{idDesarrollo}<br>
/CatalogoCorporativo/Calificacion<br>
/CatalogoCorporativo/Calificacion/{idCalificacion}<br>
<br>
<br>
<h2>/AllShopRest/rest/InformacionCuenta</h2><br>
/InformacionCuenta/Informacion/Usuario<br>
/InformacionCuenta/Informacion/Usuario<br>
/InformacionCuenta/Informacion/{idUsuario}<br>
/InformacionCuenta/Informacion/Cuenta<br>
/InformacionCuenta/Informacion/Cuenta<br>
/InformacionCuenta/Informacion/{idCuenta}<br>
<br>
<br>
<h2>/AllShopRest/rest/SeguridadCorporativa</h2>
/SeguridadCorporativa/Alias/{idAlias}<br>
/SeguridadCorporativa/Email/{idEmail}<br>
/SeguridadCorporativa/Token/{idToken}<br>
/SeguridadCorporativa/Login/{alias}/{pass}<br>
/SeguridadCorporativa/Informacion/Alias<br>
/SeguridadCorporativa/Informacion/Alias<br>
/SeguridadCorporativa/Informacion/{idAlias}<br>
</body>
</html>
