//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:31:38 PM CST 
//


package com.loam.framework.core.customer.jaxb.ws.general.headers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * -Elemento Base que
 * 				define los elementos genericos del Header Request
 * 				--ATRIBUTOS--
 * 				-locale: Informacion de localizacion del peticionario
 * 				-CodIdioma:
 * 				Formato de codificacion de caracteres
 * 
 * <p>Java class for HeaderRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Acceso" type="{http://www.loam.com/framework/core/customer/jaxb/ws/general/Headers}AccesoType"/>
 *         &lt;element name="DatosPeticion" type="{http://www.loam.com/framework/core/customer/jaxb/ws/general/Headers}RequestType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="locale">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="8"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codIdioma">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderRequestType", propOrder = {
    "acceso",
    "datosPeticion"
})
public class HeaderRequestType {

    @XmlElement(name = "Acceso", required = true)
    protected AccesoType acceso;
    @XmlElement(name = "DatosPeticion", required = true)
    protected RequestType datosPeticion;
    @XmlAttribute(name = "locale")
    protected String locale;
    @XmlAttribute(name = "codIdioma")
    protected String codIdioma;

    /**
     * Gets the value of the acceso property.
     * 
     * @return
     *     possible object is
     *     {@link AccesoType }
     *     
     */
    public AccesoType getAcceso() {
        return acceso;
    }

    /**
     * Sets the value of the acceso property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccesoType }
     *     
     */
    public void setAcceso(AccesoType value) {
        this.acceso = value;
    }

    /**
     * Gets the value of the datosPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType }
     *     
     */
    public RequestType getDatosPeticion() {
        return datosPeticion;
    }

    /**
     * Sets the value of the datosPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType }
     *     
     */
    public void setDatosPeticion(RequestType value) {
        this.datosPeticion = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the codIdioma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodIdioma() {
        return codIdioma;
    }

    /**
     * Sets the value of the codIdioma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodIdioma(String value) {
        this.codIdioma = value;
    }

}
