//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:31:38 PM CST 
//


package com.loam.framework.core.customer.jaxb.ws.customerdetails;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DataPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdPerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdPersonCat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TokenPerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NamePerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SurnamesPerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SexPerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BirthDatePerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AgePerson">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="19"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StatusFlag">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="StartDt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LastUpdateDt">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LastUpdateUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="0"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UserContactAddress" type="{http://www.loam.com/framework/core/customer/jaxb/ws/CustomerDetails}UserContactAddress" minOccurs="0"/>
 *         &lt;element name="UserContactMethod" type="{http://www.loam.com/framework/core/customer/jaxb/ws/CustomerDetails}UserContactMethod" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataPerson", propOrder = {
    "idPerson",
    "idPersonCat",
    "tokenPerson",
    "namePerson",
    "surnamesPerson",
    "sexPerson",
    "birthDatePerson",
    "agePerson",
    "idUser",
    "statusFlag",
    "startDt",
    "lastUpdateDt",
    "lastUpdateUser",
    "userContactAddress",
    "userContactMethod"
})
public class DataPerson {

    @XmlElement(name = "IdPerson", required = true)
    protected BigInteger idPerson;
    @XmlElement(name = "IdPersonCat", required = true)
    protected BigInteger idPersonCat;
    @XmlElement(name = "TokenPerson", required = true)
    protected String tokenPerson;
    @XmlElement(name = "NamePerson", required = true)
    protected String namePerson;
    @XmlElement(name = "SurnamesPerson", required = true)
    protected String surnamesPerson;
    @XmlElement(name = "SexPerson")
    protected int sexPerson;
    @XmlElement(name = "BirthDatePerson", required = true)
    protected XMLGregorianCalendar birthDatePerson;
    @XmlElement(name = "AgePerson")
    protected int agePerson;
    @XmlElement(name = "IdUser", required = true)
    protected BigInteger idUser;
    @XmlElement(name = "StatusFlag")
    protected int statusFlag;
    @XmlElement(name = "StartDt", required = true)
    protected XMLGregorianCalendar startDt;
    @XmlElement(name = "LastUpdateDt", required = true)
    protected XMLGregorianCalendar lastUpdateDt;
    @XmlElement(name = "LastUpdateUser", required = true)
    protected String lastUpdateUser;
    @XmlElement(name = "UserContactAddress")
    protected UserContactAddress userContactAddress;
    @XmlElement(name = "UserContactMethod")
    protected UserContactMethod userContactMethod;

    /**
     * Gets the value of the idPerson property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdPerson() {
        return idPerson;
    }

    /**
     * Sets the value of the idPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdPerson(BigInteger value) {
        this.idPerson = value;
    }

    /**
     * Gets the value of the idPersonCat property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdPersonCat() {
        return idPersonCat;
    }

    /**
     * Sets the value of the idPersonCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdPersonCat(BigInteger value) {
        this.idPersonCat = value;
    }

    /**
     * Gets the value of the tokenPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenPerson() {
        return tokenPerson;
    }

    /**
     * Sets the value of the tokenPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenPerson(String value) {
        this.tokenPerson = value;
    }

    /**
     * Gets the value of the namePerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePerson() {
        return namePerson;
    }

    /**
     * Sets the value of the namePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePerson(String value) {
        this.namePerson = value;
    }

    /**
     * Gets the value of the surnamesPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurnamesPerson() {
        return surnamesPerson;
    }

    /**
     * Sets the value of the surnamesPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurnamesPerson(String value) {
        this.surnamesPerson = value;
    }

    /**
     * Gets the value of the sexPerson property.
     * 
     */
    public int getSexPerson() {
        return sexPerson;
    }

    /**
     * Sets the value of the sexPerson property.
     * 
     */
    public void setSexPerson(int value) {
        this.sexPerson = value;
    }

    /**
     * Gets the value of the birthDatePerson property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDatePerson() {
        return birthDatePerson;
    }

    /**
     * Sets the value of the birthDatePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDatePerson(XMLGregorianCalendar value) {
        this.birthDatePerson = value;
    }

    /**
     * Gets the value of the agePerson property.
     * 
     */
    public int getAgePerson() {
        return agePerson;
    }

    /**
     * Sets the value of the agePerson property.
     * 
     */
    public void setAgePerson(int value) {
        this.agePerson = value;
    }

    /**
     * Gets the value of the idUser property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdUser() {
        return idUser;
    }

    /**
     * Sets the value of the idUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdUser(BigInteger value) {
        this.idUser = value;
    }

    /**
     * Gets the value of the statusFlag property.
     * 
     */
    public int getStatusFlag() {
        return statusFlag;
    }

    /**
     * Sets the value of the statusFlag property.
     * 
     */
    public void setStatusFlag(int value) {
        this.statusFlag = value;
    }

    /**
     * Gets the value of the startDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDt() {
        return startDt;
    }

    /**
     * Sets the value of the startDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDt(XMLGregorianCalendar value) {
        this.startDt = value;
    }

    /**
     * Gets the value of the lastUpdateDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * Sets the value of the lastUpdateDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdateDt(XMLGregorianCalendar value) {
        this.lastUpdateDt = value;
    }

    /**
     * Gets the value of the lastUpdateUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * Sets the value of the lastUpdateUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateUser(String value) {
        this.lastUpdateUser = value;
    }

    /**
     * Gets the value of the userContactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link UserContactAddress }
     *     
     */
    public UserContactAddress getUserContactAddress() {
        return userContactAddress;
    }

    /**
     * Sets the value of the userContactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserContactAddress }
     *     
     */
    public void setUserContactAddress(UserContactAddress value) {
        this.userContactAddress = value;
    }

    /**
     * Gets the value of the userContactMethod property.
     * 
     * @return
     *     possible object is
     *     {@link UserContactMethod }
     *     
     */
    public UserContactMethod getUserContactMethod() {
        return userContactMethod;
    }

    /**
     * Sets the value of the userContactMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserContactMethod }
     *     
     */
    public void setUserContactMethod(UserContactMethod value) {
        this.userContactMethod = value;
    }

}
