//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:31:38 PM CST 
//


package com.loam.framework.core.customer.jaxb.ws.customerdetails;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataPerson" type="{http://www.loam.com/framework/core/customer/jaxb/ws/CustomerDetails}DataPerson" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataPerson"
})
@XmlRootElement(name = "MaintainDataPersonOut")
public class MaintainDataPersonOut {

    @XmlElement(name = "DataPerson")
    protected DataPerson dataPerson;

    /**
     * Gets the value of the dataPerson property.
     * 
     * @return
     *     possible object is
     *     {@link DataPerson }
     *     
     */
    public DataPerson getDataPerson() {
        return dataPerson;
    }

    /**
     * Sets the value of the dataPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPerson }
     *     
     */
    public void setDataPerson(DataPerson value) {
        this.dataPerson = value;
    }

}
