//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:31:38 PM CST 
//


package com.loam.framework.core.customer.jaxb.ws.customerdetails;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.loam.framework.core.customer.jaxb.ws.customerdetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.loam.framework.core.customer.jaxb.ws.customerdetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultUserContactAddressIn }
     * 
     */
    public ConsultUserContactAddressIn createConsultUserContactAddressIn() {
        return new ConsultUserContactAddressIn();
    }

    /**
     * Create an instance of {@link MaintainUserContactMethodOut }
     * 
     */
    public MaintainUserContactMethodOut createMaintainUserContactMethodOut() {
        return new MaintainUserContactMethodOut();
    }

    /**
     * Create an instance of {@link ConsultDataPersonOut }
     * 
     */
    public ConsultDataPersonOut createConsultDataPersonOut() {
        return new ConsultDataPersonOut();
    }

    /**
     * Create an instance of {@link ConsultUserContactMethodIn }
     * 
     */
    public ConsultUserContactMethodIn createConsultUserContactMethodIn() {
        return new ConsultUserContactMethodIn();
    }

    /**
     * Create an instance of {@link UserAlias }
     * 
     */
    public UserAlias createUserAlias() {
        return new UserAlias();
    }

    /**
     * Create an instance of {@link MaintainDataPersonIn }
     * 
     */
    public MaintainDataPersonIn createMaintainDataPersonIn() {
        return new MaintainDataPersonIn();
    }

    /**
     * Create an instance of {@link ConsultUserContactMethodOut }
     * 
     */
    public ConsultUserContactMethodOut createConsultUserContactMethodOut() {
        return new ConsultUserContactMethodOut();
    }

    /**
     * Create an instance of {@link MaintainDataPersonOut }
     * 
     */
    public MaintainDataPersonOut createMaintainDataPersonOut() {
        return new MaintainDataPersonOut();
    }

    /**
     * Create an instance of {@link ConsultDataPersonIn }
     * 
     */
    public ConsultDataPersonIn createConsultDataPersonIn() {
        return new ConsultDataPersonIn();
    }

    /**
     * Create an instance of {@link MaintainUserContactMethodIn }
     * 
     */
    public MaintainUserContactMethodIn createMaintainUserContactMethodIn() {
        return new MaintainUserContactMethodIn();
    }

    /**
     * Create an instance of {@link MaintainUserContactAddressOut }
     * 
     */
    public MaintainUserContactAddressOut createMaintainUserContactAddressOut() {
        return new MaintainUserContactAddressOut();
    }

    /**
     * Create an instance of {@link MaintainUserAliasOut }
     * 
     */
    public MaintainUserAliasOut createMaintainUserAliasOut() {
        return new MaintainUserAliasOut();
    }

    /**
     * Create an instance of {@link DataPerson }
     * 
     */
    public DataPerson createDataPerson() {
        return new DataPerson();
    }

    /**
     * Create an instance of {@link MaintainUserContactAddressIn }
     * 
     */
    public MaintainUserContactAddressIn createMaintainUserContactAddressIn() {
        return new MaintainUserContactAddressIn();
    }

    /**
     * Create an instance of {@link ConsultUserAliasIn }
     * 
     */
    public ConsultUserAliasIn createConsultUserAliasIn() {
        return new ConsultUserAliasIn();
    }

    /**
     * Create an instance of {@link ConsultUserContactAddressOut }
     * 
     */
    public ConsultUserContactAddressOut createConsultUserContactAddressOut() {
        return new ConsultUserContactAddressOut();
    }

    /**
     * Create an instance of {@link UserContactMethod }
     * 
     */
    public UserContactMethod createUserContactMethod() {
        return new UserContactMethod();
    }

    /**
     * Create an instance of {@link UserContactAddress }
     * 
     */
    public UserContactAddress createUserContactAddress() {
        return new UserContactAddress();
    }

    /**
     * Create an instance of {@link ConsultUserAliasOut }
     * 
     */
    public ConsultUserAliasOut createConsultUserAliasOut() {
        return new ConsultUserAliasOut();
    }

    /**
     * Create an instance of {@link MaintainUserAliasIn }
     * 
     */
    public MaintainUserAliasIn createMaintainUserAliasIn() {
        return new MaintainUserAliasIn();
    }

}
