//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:34:47 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.loam.com/framework/core/security/jaxb/ws/common/ExcepcionGeneral")
package com.loam.framework.core.security.jaxb.ws.common.excepciongeneral;
