//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.19 at 04:25:48 PM CST 
//


package com.loam.framework.core.catalog.jaxb.ws.catalogmanager;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.loam.framework.core.catalog.jaxb.ws.catalogmanager package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.loam.framework.core.catalog.jaxb.ws.catalogmanager
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultCatalogSubCategoryOut }
     * 
     */
    public ConsultCatalogSubCategoryOut createConsultCatalogSubCategoryOut() {
        return new ConsultCatalogSubCategoryOut();
    }

    /**
     * Create an instance of {@link ConsultCatalogCoinIn }
     * 
     */
    public ConsultCatalogCoinIn createConsultCatalogCoinIn() {
        return new ConsultCatalogCoinIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogCategoryOut }
     * 
     */
    public ConsultCatalogCategoryOut createConsultCatalogCategoryOut() {
        return new ConsultCatalogCategoryOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogRolOut }
     * 
     */
    public MaintainCatalogRolOut createMaintainCatalogRolOut() {
        return new MaintainCatalogRolOut();
    }

    /**
     * Create an instance of {@link ConsultCatalogContactMethodOut }
     * 
     */
    public ConsultCatalogContactMethodOut createConsultCatalogContactMethodOut() {
        return new ConsultCatalogContactMethodOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogRolIn }
     * 
     */
    public MaintainCatalogRolIn createMaintainCatalogRolIn() {
        return new MaintainCatalogRolIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogMenuIn }
     * 
     */
    public ConsultCatalogMenuIn createConsultCatalogMenuIn() {
        return new ConsultCatalogMenuIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogContactMethodIn }
     * 
     */
    public MaintainCatalogContactMethodIn createMaintainCatalogContactMethodIn() {
        return new MaintainCatalogContactMethodIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogRolOut }
     * 
     */
    public ConsultCatalogRolOut createConsultCatalogRolOut() {
        return new ConsultCatalogRolOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogSubCategoryOut }
     * 
     */
    public MaintainCatalogSubCategoryOut createMaintainCatalogSubCategoryOut() {
        return new MaintainCatalogSubCategoryOut();
    }

    /**
     * Create an instance of {@link CatalogCoin }
     * 
     */
    public CatalogCoin createCatalogCoin() {
        return new CatalogCoin();
    }

    /**
     * Create an instance of {@link ConsultCatalogRolMenuIn }
     * 
     */
    public ConsultCatalogRolMenuIn createConsultCatalogRolMenuIn() {
        return new ConsultCatalogRolMenuIn();
    }

    /**
     * Create an instance of {@link CatalogProduct }
     * 
     */
    public CatalogProduct createCatalogProduct() {
        return new CatalogProduct();
    }

    /**
     * Create an instance of {@link MaintainCatalogCategoryOut }
     * 
     */
    public MaintainCatalogCategoryOut createMaintainCatalogCategoryOut() {
        return new MaintainCatalogCategoryOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogContactMethodOut }
     * 
     */
    public MaintainCatalogContactMethodOut createMaintainCatalogContactMethodOut() {
        return new MaintainCatalogContactMethodOut();
    }

    /**
     * Create an instance of {@link ConsultCatalogMenuOut }
     * 
     */
    public ConsultCatalogMenuOut createConsultCatalogMenuOut() {
        return new ConsultCatalogMenuOut();
    }

    /**
     * Create an instance of {@link CatalogAccount }
     * 
     */
    public CatalogAccount createCatalogAccount() {
        return new CatalogAccount();
    }

    /**
     * Create an instance of {@link MaintainCatalogMenuIn }
     * 
     */
    public MaintainCatalogMenuIn createMaintainCatalogMenuIn() {
        return new MaintainCatalogMenuIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogRolMenuIn }
     * 
     */
    public MaintainCatalogRolMenuIn createMaintainCatalogRolMenuIn() {
        return new MaintainCatalogRolMenuIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogCoinOut }
     * 
     */
    public ConsultCatalogCoinOut createConsultCatalogCoinOut() {
        return new ConsultCatalogCoinOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogAccountOut }
     * 
     */
    public MaintainCatalogAccountOut createMaintainCatalogAccountOut() {
        return new MaintainCatalogAccountOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogColorOut }
     * 
     */
    public MaintainCatalogColorOut createMaintainCatalogColorOut() {
        return new MaintainCatalogColorOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogMenuOut }
     * 
     */
    public MaintainCatalogMenuOut createMaintainCatalogMenuOut() {
        return new MaintainCatalogMenuOut();
    }

    /**
     * Create an instance of {@link CatalogContactMethod }
     * 
     */
    public CatalogContactMethod createCatalogContactMethod() {
        return new CatalogContactMethod();
    }

    /**
     * Create an instance of {@link ConsultCatalogAccountIn }
     * 
     */
    public ConsultCatalogAccountIn createConsultCatalogAccountIn() {
        return new ConsultCatalogAccountIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogCoinOut }
     * 
     */
    public MaintainCatalogCoinOut createMaintainCatalogCoinOut() {
        return new MaintainCatalogCoinOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogColorIn }
     * 
     */
    public MaintainCatalogColorIn createMaintainCatalogColorIn() {
        return new MaintainCatalogColorIn();
    }

    /**
     * Create an instance of {@link AccountProduct }
     * 
     */
    public AccountProduct createAccountProduct() {
        return new AccountProduct();
    }

    /**
     * Create an instance of {@link ConsultCatalogContactMethodIn }
     * 
     */
    public ConsultCatalogContactMethodIn createConsultCatalogContactMethodIn() {
        return new ConsultCatalogContactMethodIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogAccountOut }
     * 
     */
    public ConsultCatalogAccountOut createConsultCatalogAccountOut() {
        return new ConsultCatalogAccountOut();
    }

    /**
     * Create an instance of {@link ConsultCatalogProductIn }
     * 
     */
    public ConsultCatalogProductIn createConsultCatalogProductIn() {
        return new ConsultCatalogProductIn();
    }

    /**
     * Create an instance of {@link CatalogCategory }
     * 
     */
    public CatalogCategory createCatalogCategory() {
        return new CatalogCategory();
    }

    /**
     * Create an instance of {@link ConsultCatalogCategoryIn }
     * 
     */
    public ConsultCatalogCategoryIn createConsultCatalogCategoryIn() {
        return new ConsultCatalogCategoryIn();
    }

    /**
     * Create an instance of {@link CatalogSubCategory }
     * 
     */
    public CatalogSubCategory createCatalogSubCategory() {
        return new CatalogSubCategory();
    }

    /**
     * Create an instance of {@link MaintainCatalogSubCategoryIn }
     * 
     */
    public MaintainCatalogSubCategoryIn createMaintainCatalogSubCategoryIn() {
        return new MaintainCatalogSubCategoryIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogProductOut }
     * 
     */
    public MaintainCatalogProductOut createMaintainCatalogProductOut() {
        return new MaintainCatalogProductOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogRolMenuOut }
     * 
     */
    public MaintainCatalogRolMenuOut createMaintainCatalogRolMenuOut() {
        return new MaintainCatalogRolMenuOut();
    }

    /**
     * Create an instance of {@link CatalogMenu }
     * 
     */
    public CatalogMenu createCatalogMenu() {
        return new CatalogMenu();
    }

    /**
     * Create an instance of {@link ConsultCatalogRolIn }
     * 
     */
    public ConsultCatalogRolIn createConsultCatalogRolIn() {
        return new ConsultCatalogRolIn();
    }

    /**
     * Create an instance of {@link ConsultCatalogColorOut }
     * 
     */
    public ConsultCatalogColorOut createConsultCatalogColorOut() {
        return new ConsultCatalogColorOut();
    }

    /**
     * Create an instance of {@link ConsultCatalogSubCategoryIn }
     * 
     */
    public ConsultCatalogSubCategoryIn createConsultCatalogSubCategoryIn() {
        return new ConsultCatalogSubCategoryIn();
    }

    /**
     * Create an instance of {@link CatalogColor }
     * 
     */
    public CatalogColor createCatalogColor() {
        return new CatalogColor();
    }

    /**
     * Create an instance of {@link ConsultCatalogRolMenuOut }
     * 
     */
    public ConsultCatalogRolMenuOut createConsultCatalogRolMenuOut() {
        return new ConsultCatalogRolMenuOut();
    }

    /**
     * Create an instance of {@link MaintainCatalogProductIn }
     * 
     */
    public MaintainCatalogProductIn createMaintainCatalogProductIn() {
        return new MaintainCatalogProductIn();
    }

    /**
     * Create an instance of {@link CatalogRol }
     * 
     */
    public CatalogRol createCatalogRol() {
        return new CatalogRol();
    }

    /**
     * Create an instance of {@link ConsultCatalogProductOut }
     * 
     */
    public ConsultCatalogProductOut createConsultCatalogProductOut() {
        return new ConsultCatalogProductOut();
    }

    /**
     * Create an instance of {@link CatalogRolMenu }
     * 
     */
    public CatalogRolMenu createCatalogRolMenu() {
        return new CatalogRolMenu();
    }

    /**
     * Create an instance of {@link ConsultCatalogColorIn }
     * 
     */
    public ConsultCatalogColorIn createConsultCatalogColorIn() {
        return new ConsultCatalogColorIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogCategoryIn }
     * 
     */
    public MaintainCatalogCategoryIn createMaintainCatalogCategoryIn() {
        return new MaintainCatalogCategoryIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogAccountIn }
     * 
     */
    public MaintainCatalogAccountIn createMaintainCatalogAccountIn() {
        return new MaintainCatalogAccountIn();
    }

    /**
     * Create an instance of {@link MaintainCatalogCoinIn }
     * 
     */
    public MaintainCatalogCoinIn createMaintainCatalogCoinIn() {
        return new MaintainCatalogCoinIn();
    }

}
