//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:34:47 PM CST 
//


package com.loam.framework.core.security.jaxb.ws.corporatesecurity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.loam.framework.core.security.jaxb.ws.corporatesecurity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.loam.framework.core.security.jaxb.ws.corporatesecurity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SecurityLoginOut }
     * 
     */
    public SecurityLoginOut createSecurityLoginOut() {
        return new SecurityLoginOut();
    }

    /**
     * Create an instance of {@link SecurityEmailOut }
     * 
     */
    public SecurityEmailOut createSecurityEmailOut() {
        return new SecurityEmailOut();
    }

    /**
     * Create an instance of {@link SecurityTokenOut }
     * 
     */
    public SecurityTokenOut createSecurityTokenOut() {
        return new SecurityTokenOut();
    }

    /**
     * Create an instance of {@link SecurityLogin }
     * 
     */
    public SecurityLogin createSecurityLogin() {
        return new SecurityLogin();
    }

    /**
     * Create an instance of {@link SecurityAliasIn }
     * 
     */
    public SecurityAliasIn createSecurityAliasIn() {
        return new SecurityAliasIn();
    }

    /**
     * Create an instance of {@link SecurityTokenIn }
     * 
     */
    public SecurityTokenIn createSecurityTokenIn() {
        return new SecurityTokenIn();
    }

    /**
     * Create an instance of {@link SecurityAliasOut }
     * 
     */
    public SecurityAliasOut createSecurityAliasOut() {
        return new SecurityAliasOut();
    }

    /**
     * Create an instance of {@link SecurityLoginIn }
     * 
     */
    public SecurityLoginIn createSecurityLoginIn() {
        return new SecurityLoginIn();
    }

    /**
     * Create an instance of {@link SecurityEmailIn }
     * 
     */
    public SecurityEmailIn createSecurityEmailIn() {
        return new SecurityEmailIn();
    }

}
