//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.18 at 05:34:47 PM CST 
//


package com.loam.framework.core.security.jaxb.ws.corporatesecurity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tokenTemp">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AliasUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PassUser">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tokenTemp",
    "aliasUser",
    "passUser"
})
@XmlRootElement(name = "SecurityLoginIn")
public class SecurityLoginIn {

    @XmlElement(required = true)
    protected String tokenTemp;
    @XmlElement(name = "AliasUser", required = true)
    protected String aliasUser;
    @XmlElement(name = "PassUser", required = true)
    protected String passUser;

    /**
     * Gets the value of the tokenTemp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenTemp() {
        return tokenTemp;
    }

    /**
     * Sets the value of the tokenTemp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenTemp(String value) {
        this.tokenTemp = value;
    }

    /**
     * Gets the value of the aliasUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasUser() {
        return aliasUser;
    }

    /**
     * Sets the value of the aliasUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasUser(String value) {
        this.aliasUser = value;
    }

    /**
     * Gets the value of the passUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassUser() {
        return passUser;
    }

    /**
     * Sets the value of the passUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassUser(String value) {
        this.passUser = value;
    }

}
